version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: skill_sheet_backend_development
      POSTGRES_USER: skill_sheet_backend
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/skill_sheet_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true #dockerコンテナを起動したままにできる。コンテナ内に入ってコマンドを打ち込める
    tty: true        #コンテナを起動させたまま、bashで入れたりできる
    environment:
      DATABASE_URL: postgres://skill_sheet_backend:password@db:5432/skill_sheet_backend_development

volumes:
  postgres-data:
